#161348796 Users should be able to create their profiles
andela/ah-backend-thanos pull request #13
Opened 2018-10-31 17:46 UTC by RachaelNantale

#### What does this PR do?

Create User profiles when a user registers
- ##### Endpoints
`GET /api/profiles`  for viewing other users' profiles
`PUT /api/profile/<username>` for updating your profile
#### Description of Task to be completed?

- Create a profile when a user is created simultaneously.

-  Edit the user profile and not other user's profiles

- View other users' profiles
-  Profile displays username, bio, last name, first name and image
- A timestamp for when the user is created and also when the profile is updated

#### How should this be manually tested?

- Run `python manage.py runserver` to run the server
In postman using:
To register a user.
url: `api/users`
Payload:
```
{  "user":{
	  "email":"test@test.com",
	  "username": "test",
	  "password":"test1234"
   }
}
```
To view a user profile
url: `api/profiles/<username>`
Payload:
```
{  "profiles": {
        "username": "jude",
        "bio": "",
        "image": "",
        "first_name": "",
        "last_name": "",
        "created_at": "2018-10-31T14:08:33.254477Z",
        "updated_at": "2018-10-31T14:08:33.254500Z"
    }
   }
}
```
To view all Profiles
url `api/profiles`
Payload
```[
    {
        "username": "rachaelm",
        "bio": "",
        "image": "",
        "first_name": "",
        "last_name": "",
        "created_at": "2018-10-31T17:14:20.119177Z",
        "updated_at": "2018-10-31T17:14:20.119196Z"
    }
]
```
- Using postman test the endpoints above.
- On successful registration or login, a token is returned with the user credentials.

#### Any background context you want to provide?

- For a Profile to be created, a user has to be succesfully registered. When logged in, the user token is the unique identifier of the user. No other user can edit another's profile.

#### What are the relevant pivotal tracker stories?

[#161348796](https://www.pivotaltracker.com/story/show/161348796)

2018-11-01 07:35 UTC, emugaya requested changes
Let's have one migration file. Why do we have 32 files changed? collapse the new migrations file into one.

2018-11-01 08:42 UTC, RachaelNantale commented
I have squashed the migrations as requested.
I have 32 files because 

- I made a few changes to the authentication app to suit the profile app since the user and user profile are created simultaneously

- I also created a new profile app which needs files  unique to like `serializer.py`

- Some of the files didnt follow the PEP8 standards

2018-11-01 13:16 UTC, judeinno approved these changes

2018-11-01 13:16 UTC, judeinno commented on authors/apps/authentication/tests_auth/test_login.py
>          )
Good work, formatting the work to pep8 standards

2018-11-02 05:01 UTC, emugaya approved these changes

2018-11-02 05:02 UTC, merged