feature(rate an article): Users should be able to rate an article.
andela/ah-backend-thanos pull request #23
Opened 2018-11-07 09:30 UTC by dnuwa

#### What does this PR do?
- Rate an article
- Get a rating for a single article

#### How should this be manually tested?
POST `/api/articles/<id>/rating`
GET `/api/articles/<id>/rating`

```
 { 
       "rating":4
}
```

Example response:
```
{
    "article_scores": [
        {
            "rating": 4,
            "reader": {
                "username": "daniel1",
                "article_slug": "how-to-create-your-dance-moves"
            },
            "article": 1
        }
    ]
}
```

#### Any background context you want to provide?
- A user has to be  logged in to rate an article
- A user can not rate an article published by themselves
- The rating score should be between 0 and 5

#### What are the relevant pivotal tracker stories?
[#161348798](https://www.pivotaltracker.com/story/show/161348798)

2018-11-07 09:37 UTC, judeinno commented
Please work on the hound violations and test coverage

2018-11-07 20:26 UTC, emugaya requested changes
Hey, What do you return when a rating has been added. Is it the rating average or the chole rating the user supplied. I suggest you sync with the PO on this for clarification on wht you should return.

2018-11-08 06:23 UTC, brucemakallan commented on authors/apps/articles/tests_articles/test_articles.py
> +    def test_user_rates_an_article_twice(self):
Let's try and refactor these tests to avoid repetition

2018-11-08 11:14 UTC, emugaya commented on authors/apps/profiles/views.py
> +            user_id, username, email = get_id_from_token(request)
No need for this.

2018-11-08 11:15 UTC, emugaya commented on authors/apps/core/utils/user_management.py
> +    return payload['id'], payload['username'], payload['email']
No need for this.

2018-11-08 11:16 UTC, emugaya commented on authors/apps/articles/views.py
> +    def list(self, request, *args, **kwargs):
Remove this method.

2018-11-08 11:16 UTC, emugaya commented on authors/apps/articles/views.py
> +            return Response({"error": "You can't rate your article"},
raise Bad request exception

2018-11-08 11:17 UTC, emugaya commented on authors/apps/articles/views.py
> +            return Response(
raise Bad request exception

2018-11-08 11:17 UTC, emugaya commented on authors/apps/articles/views.py
> +        author_id, username, email = get_id_from_token(request)
remove email

2018-11-08 11:17 UTC, emugaya commented on authors/apps/articles/views.py
> +        author_id, author_username, email = get_id_from_token(request)
remove email

2018-11-08 11:17 UTC, emugaya commented on authors/apps/articles/views.py
> +        author_id, author_username, email = get_id_from_token(request)
remove email

2018-11-08 11:18 UTC, emugaya commented on authors/apps/articles/urls.py
> +
why do you have this line

2018-11-08 11:19 UTC, emugaya commented on authors/apps/articles/views.py
> +    post:rate an article
Look best practices of docstrings

2018-11-08 11:20 UTC, emugaya commented on authors/apps/articles/views.py
> +    """
Write better docstrings

2018-11-08 19:18 UTC, merged