#161348802 Favorite an article
andela/ah-backend-thanos pull request #30
Opened 2018-11-08 14:14 UTC by judeinno

#### What does this PR do?
- Ensure that users can favorite an article.
- Ensure that the user can update favorite status.
- Refactor test to use basetest file.

#### Description of Task to be completed?
Have the following endpoints working;
`POST|GET /api/articles/<int:article_id>/favorite_status`
`PUT /api/articles/<int:article_id>/favorite_status_update`

#### How should this be manually tested?
Using post man to test the endpoints above
To Favorite an article
URL: `POST|GET /api/articles/<int:article_id>/favorite_status`
Payload
````
{
	"favorite_status": "True"
}
````
Response:
````
{
    "favorite_status": [
        {
            "id": 1,
            "favorite_status": true,
            "article": 1,
            "user": "judeinno"
        }
    ]
}
````
To update the favorite status
URL: `PUT /api/articles/<int:article_id>/favorite_status_update`
Payload
````
{
	"favorite_status": "False"
}
````
Response
````
{
    "favorite_status": {
        "favorite_status": false
    }
}
````
#### What are the relevant pivotal tracker stories?
[#161348802](https://www.pivotaltracker.com/story/show/161348802)

2018-11-09 07:05 UTC, emugaya approved these changes

2018-11-12 13:41 UTC, judeinno commented
@emugaya The user can now get his/her favourite articles once logged in.

2018-11-12 15:29 UTC, Sulaiman-Mozes approved these changes

2018-11-12 15:34 UTC, RachaelNantale approved these changes

2018-11-13 11:30 UTC, emugaya requested changes
Please implement the feedback I gave on migrations yesterday

2018-11-13 12:41 UTC, judeinno commented
@emugaya I have finished working on the feedback given yesterday please review.

2018-11-13 13:44 UTC, emugaya approved these changes

2018-11-13 13:45 UTC, merged