#161872375 Code refactor for followers
andela/ah-backend-thanos pull request #32
Opened 2018-11-12 09:30 UTC by brucemakallan

#### What does this PR do?
Change the JSON representation of Followers

#### Description of Task to be completed?
- Change JSON to remove the 'follower' and 'followee' dictionary keys
- Display profiles without any extra dictionary keys

#### How should this be manually tested?
GET `/api/users/3/followers`
GET `/api/users/1/following`

Both should return a list of profiles as seen below:
```
{
    "profiles": [
        {
            "id": 2,
            "username": "jackkatto",
            "first_name": "Jack",
            "last_name": "Katto",
            "bio": "Test bio"
        },
        {
            "id": 3,
            "username": "judeinno",
            "first_name": "Jude",
            "last_name": "Inno",
            "bio": "Test jude bio"
        }
    ]
}
```

#### Any background context you want to provide?
You require authentication to view followers and user following a specific user 

#### What are the relevant pivotal tracker stories?
[#161872375](https://www.pivotaltracker.com/story/show/161872375)

2018-11-12 15:54 UTC, judeinno commented on authors/apps/profiles/serializers.py
> +        return (ProfileSerializer(profile).data)
I like the way you refactored the serializers to use one serializer, Great job

2018-11-12 15:58 UTC, judeinno approved these changes
LGTM

2018-11-13 05:11 UTC, RachaelNantale approved these changes
LGTM

2018-11-13 11:32 UTC, emugaya requested changes
Please follow the advice I gave on migrations yesterday

2018-11-13 16:36 UTC, merged