#161877838  Refactor Json response format for consistency
andela/ah-backend-thanos pull request #33
Opened 2018-11-12 12:16 UTC by RachaelNantale

#### What does this PR do?
Change the JSON response format for consistency

#### Description of Task to be completed?
- Change JSON to remove the 'follower' and 'followee' dictionary keys
- Display articles without any extra dictionary keys

#### How should this be manually tested?
GET `/api/articles/1/comments`
GET `/api/articles/1/comments/1/threads`
GET `/api/articles/1/like_status`

Both should return a list of profiles as seen below:
```
{
    "comments": [
        {
            "id": 4,
            "comment_body": "Yes surely PHP is great",
            "comment_author": {
                "id": 1,
                "username": "rachaelminani",
                "email": "rachaelminani42@gmail.com"
            },
            "created_at": "2018-11-12T10:03:26.946858Z",
            "updated_at": "2018-11-12T10:03:26.946887Z"
        },
        {
            "id": 5,
            "comment_body": "Yes surely PHP is great",
            "comment_author": {
                "id": 1,
                "username": "rachaelminani",
                "email": "rachaelminani42@gmail.com"
            },
            "created_at": "2018-11-12T10:04:02.880563Z",
            "updated_at": "2018-11-12T10:04:02.880586Z"
        }
   ]
}

```
```
{
    "threads": [
        {
            "id": 7,
            "thread_body": "here here",
            "thread_author": {
                "id": 1,
                "username": "rachaelminani",
                "email": "rachaelminani42@gmail.com"
            },
            "created_at": "2018-11-12T11:26:56.561274Z",
            "updated_at": "2018-11-12T11:26:56.561301Z"
        }
    ]
}
```

#### Any background context you want to provide?
- A user has to be  logged in to comment on an article
- User can comment on  both authored by me and those not authored by him/her
- You must be the author of the article in order to edit it
 

#### What are the relevant pivotal tracker stories?
[#161877838](https://www.pivotaltracker.com/story/show/161877838)

2018-11-12 15:38 UTC, judeinno approved these changes
Good work refactoring the error messages keys.

2018-11-12 15:56 UTC, brucemakallan approved these changes

2018-11-12 15:56 UTC, brucemakallan commented on authors/apps/profiles/renderers.py
> -    def render(self, data, media_type=None, renderer_context=None):
Thanks for saving us from repeated code. Great work harmonizing the JSON responses

2018-11-13 11:34 UTC, emugaya requested changes
Follow the advice I gave on migrations yesterday

2018-11-13 14:30 UTC, dnuwa approved these changes

2018-11-13 15:29 UTC, emugaya approved these changes

2018-11-13 15:29 UTC, merged