feat(notifications): Users receives notifications
andela/ah-backend-thanos pull request #44
Opened 2018-11-15 14:36 UTC by judeinno

#### What does this PR do?
- Add a subscription field to the user model.
- Create a notification utility
- Notify followers when an article is created by a user they follow.
- Notify a user when an article they favourite gets a new comment.
- Add an endpoint to update subscription
- Use honcho to run the server on deployment.
- Use celery to make the notifications sent to run in the background.

#### Description of Task to be completed?
Have the following endpoints working;
`PUT /api/users/<int:pk>/unsubscribe`

#### How should this be manually tested?
Using post man to test the endpoints above
To Favorite an article
URL: `PUT /api/users/<int:pk>/unsubscribe`
Payload
````
{"is_subscribed": "False"}
````

#### What are the relevant pivotal tracker stories?
[#161348804](https://www.pivotaltracker.com/story/show/161348804)

2018-11-15 19:00 UTC, emugaya requested changes
How do I set up the notification job??? Share steps on how this is set up. Also update the README and Wiki

2018-11-15 19:00 UTC, emugaya commented on .coveragerc
> +    */celery.py
Why are you ignoring this file Just delete it.

2018-11-16 03:45 UTC, judeinno commented on .coveragerc
> +    */celery.py
Its part of the celery setup

2018-11-19 19:54 UTC, emugaya approved these changes

2018-11-19 19:54 UTC, merged